foreground_conditioned_examples = [
    [
        "imgs/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Right Light",
        512,
        960,
        12345,
        "imgs/o1.png",
    ],
    [
        "imgs/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Left Light",
        512,
        960,
        50,
        "imgs/o2.png",
    ],
    [
        "imgs/i3.png",
        "beautiful woman, detailed face, neon light, city",
        "Left Light",
        512,
        768,
        12345,
        "imgs/o3.png",
    ],
    [
        "imgs/i3.png",
        "beautiful woman, detailed face, sunshine from window",
        "Left Light",
        512,
        768,
        12345,
        "imgs/o4.png",
    ],
    [
        "imgs/i5.png",
        "beautiful woman, detailed face, warm atmosphere, at home, bedroom",
        "Left Light",
        512,
        768,
        123,
        "imgs/o5.png",
    ],
    [
        "imgs/i6.jpg",
        "beautiful woman, detailed face, sunshine from window",
        "Right Light",
        512,
        768,
        42,
        "imgs/o6.png",
    ],
    [
        "imgs/i7.jpg",
        "beautiful woman, detailed face, shadow from window",
        "Left Light",
        512,
        768,
        8888,
        "imgs/o7.png",
    ],
    [
        "imgs/i8.webp",
        "beautiful woman, detailed face, sunset over sea",
        "Right Light",
        512,
        640,
        42,
        "imgs/o8.png",
    ],
    [
        "imgs/i9.png",
        "handsome boy, detailed face, neon light, city",
        "Left Light",
        512,
        640,
        12345,
        "imgs/o9.png",
    ],
    [
        "imgs/i10.png",
        "beautiful woman, detailed face, light and shadow",
        "Left Light",
        512,
        960,
        65123,
        "imgs/o10.png",
    ],
    [
        "imgs/i11.png",
        "Buddha, detailed face, sci-fi RGB glowing, cyberpunk",
        "Left Light",
        512,
        768,
        8888,
        "imgs/o11.png",
    ],
    [
        "imgs/i11.png",
        "Buddha, detailed face, natural lighting",
        "Left Light",
        512,
        768,
        12345,
        "imgs/o12.png",
    ],
    [
        "imgs/i13.png",
        "toy, detailed face, shadow from window",
        "Bottom Light",
        512,
        704,
        12345,
        "imgs/o13.png",
    ],
    [
        "imgs/i14.png",
        "toy, detailed face, sunset over sea",
        "Right Light",
        512,
        704,
        100,
        "imgs/o14.png",
    ],
    [
        "imgs/i15.png",
        "dog, magic lit, sci-fi RGB glowing, studio lighting",
        "Bottom Light",
        512,
        768,
        12345,
        "imgs/o15.png",
    ],
    [
        "imgs/i16.png",
        "mysteriou human, warm atmosphere, warm atmosphere, at home, bedroom",
        "Right Light",
        512,
        768,
        100,
        "imgs/o16.png",
    ],
]

bg_samples = [
    'imgs/bgs/1.webp',
    'imgs/bgs/2.webp',
    'imgs/bgs/3.webp',
    'imgs/bgs/4.webp',
    'imgs/bgs/5.webp',
    'imgs/bgs/6.webp',
    'imgs/bgs/7.webp',
    'imgs/bgs/8.webp',
    'imgs/bgs/9.webp',
    'imgs/bgs/10.webp',
    'imgs/bgs/11.png',
    'imgs/bgs/12.png',
    'imgs/bgs/13.png',
    'imgs/bgs/14.png',
    'imgs/bgs/15.png',
]

background_conditioned_examples = [
    [
        "imgs/alter/i2.png",
        "imgs/bgs/11.png",
        "statue of an angel, natural lighting",
        "Use Flipped Background Image",
        512,
        768,
        12345,
        "imgs/alter/o2.png",
    ]
]
