foreground_conditioned_examples = [
    [
        "imgs/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Right Light",
        512,
        960,
        2,
        12345,
        "imgs/o1.png",
    ],
    [
        "imgs/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Left Light",
        512,
        960,
        2,
        50,
        "imgs/o2.png",
    ],
    [
        "imgs/i3.png",
        "beautiful woman, detailed face, neon light, city",
        "Left Light",
        512,
        768,
        2,
        12345,
        "imgs/o3.png",
    ],
    [
        "imgs/i3.png",
        "beautiful woman, detailed face, sunshine from window",
        "Left Light",
        512,
        768,
        2,
        12345,
        "imgs/o4.png",
    ],
]
