foreground_conditioned_examples = [
    [
        "imgs/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Right Light",
        512,
        960,
        2,
        12345,
        "imgs/o1.png",
    ],
    [
        "imgs/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Left Light",
        512,
        960,
        2,
        50,
        "imgs/o2.png",
    ],
    [
        "imgs/i3.png",
        "beautiful woman, detailed face, neon light, city",
        "Left Light",
        512,
        768,
        2,
        12345,
        "imgs/o3.png",
    ],
    [
        "imgs/i3.png",
        "beautiful woman, detailed face, sunshine from window",
        "Left Light",
        512,
        768,
        2,
        12345,
        "imgs/o4.png",
    ],
    [
        "imgs/i5.png",
        "beautiful woman, detailed face, warm atmosphere, at home, bedroom",
        "Left Light",
        512,
        768,
        2,
        123,
        "imgs/o5.png",
    ],
    [
        "imgs/i6.jpg",
        "beautiful woman, detailed face, sunshine from window",
        "Right Light",
        512,
        768,
        2,
        42,
        "imgs/o6.png",
    ],
    [
        "imgs/i7.jpg",
        "beautiful woman, detailed face, shadow from window",
        "Left Light",
        512,
        768,
        2,
        8888,
        "imgs/o7.png",
    ],
]
